set nocompatible
syntax on
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set number
set laststatus=2
set ruler
set backspace=indent,eol,start
set ignorecase
set smartcase
set incsearch
color purify
set autoindent
